display_full_path = true
search_submodules = false
recursive_submodules = false
switch_filter_unknown = false
excluded_dirs = ["/home/asx/code/other"]
search_paths = [
    "$HOME/.config/nvim",
    "$HOME/.config/hypr",
    "$HOME/code/cv",
    "$HOME/code/microsoft",
]
bookmarks = ["$HOME/.obsidian/default"]

[[search_dirs]]
path = "$HOME/code"
depth = 1
