#!/bin/sh


export XDG_CURRENT_DESKTOP=river

systemctl --user import-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP

# dbus-update-activation-environment WAYLAND_DISPLAY DISPLAY XDG_CURRENT_DESKTOP PATH

systemd-notify --ready

kanshi &
awww-daemon &

exec /home/asx/applications/kwm
