monitor.alsa.rules = [
  {
    matches = [
      {
        node.name= "~alsa_output.usb-GuangZhou_FiiO_Electronics_Co._Ltd_FIIO_K13_R2R*"
      }
    ]
    actions = {
      update-props = {
        priority.session = 10000
        audio.rate = 192000
      }
    }
  }
]
